/*Obras */
const carrusel = document.getElementById('carouselExampleCaptions');
const sinopsisDiv = document.getElementById('sinopsis-texto');
const analisisDiv = document.getElementById('analisis');

function actualizarSinopsis() {
    //Encontrar el título del libro actualmente ACTIVO
    //Buscar el elemento con la clase 'active' dentro del carrusel, y luego su h5
    const tituloElemento = document.querySelector('.carousel-item.active h5');
    
    //extraer el texto del titulo
    const titulo = tituloElemento ? tituloElemento.textContent.trim() : ""; // .trim() saca espacios
    if (titulo === "Sentido y sensibilidad") {
        sinopsisDiv.textContent = "Sentido y Sensibilidad cuenta la historia de las hermanas Dashwood, Elinor y Marianne, que enfrentan la pérdida de su hogar y la precariedad económica tras la muerte de su padre. Mientras Elinor encarna la prudencia y la razón, Marianne se deja guiar por la pasión y la emoción. Sus vidas amorosas se ven puestas a prueba: Marianne se enamora de un joven atractivo pero engañoso, mientras que Elinor lidia con un afecto secreto y complicado hacia Edward Ferrars. La novela explora cómo la sensatez y la sensibilidad influyen en el amor, la familia y las decisiones en la Inglaterra rural del siglo XIX.";
        analisisDiv.textContent = "Jane Austen comenzó a escribirla alrededor de 1795 con el título provisional Elinor y Marianne, y la revisó considerablemente en 1809 antes de publicarla en 1811, pagando incluso parte de la edición. Como primera novela publicada de Austen, ya mostraba las características que serían su sello distintivo: observación perspicaz de la sociedad, personajes bien delineados y un ingenio sutil que combina crítica social y humor. La obra explora el contraste entre la sensatez y la sensibilidad, encarnadas en las hermanas Elinor y Marianne, y plantea la pregunta de si la mejor manera de vivir es equilibrar la razón y la emoción, o inclinarse hacia una de ellas. Desde su publicación, la novela recibió críticas favorables, elogiando su originalidad y estilo elegante, y ha sido objeto de numerosos estudios literarios que destacan su compleja construcción de personajes y su visión de las relaciones humanas y la posición de la mujer en la sociedad inglesa de principios del siglo XIX.";
    } else if (titulo === "Orgullo y prejuicio") {
        sinopsisDiv.textContent = "Orgullo y Prejuicio narra la historia de Elizabeth Bennet, una joven inteligente y perspicaz que forma parte de una familia de clase media con cinco hermanas. La vida de Elizabeth se complica cuando conoce al adinerado y orgulloso Sr. Darcy. Inicialmente, ambos se sienten repelidos por los defectos del otro: Elizabeth por su orgullo y Darcy por sus prejuicios hacia su familia y posición social. A medida que se enfrentan a malentendidos, diferencias sociales y rivalidades familiares, aprenden a superar sus errores y prejuicios. La novela explora temas como el matrimonio, la posición social, el amor verdadero y la importancia de la introspección.";
        analisisDiv.textContent = "Publicada por primera vez en 1813, consolidó a Jane Austen como una autora destacada de la literatura inglesa. La novela combina un agudo sentido del humor, crítica social y desarrollo profundo de personajes, especialmente de mujeres jóvenes que buscan equilibrar sus deseos personales con las expectativas sociales. El título refleja los rasgos centrales de los protagonistas: el orgullo de Darcy y los prejuicios de Elizabeth. Austen desarrolla con maestría la tensión entre estas características, mostrando cómo la reflexión y la autocrítica permiten a los personajes evolucionar. Desde su publicación, la obra recibió elogios por su ingenio, originalidad y realismo. Ha sido ampliamente estudiada por críticos y académicos, adaptada innumerables veces al cine, la televisión y el teatro, y continúa siendo una de las novelas más leídas y queridas de la literatura inglesa, destacándose tanto por su entretenimiento como por su visión crítica de las normas sociales de la época."
    } else if (titulo === "Parque Mansfield") {
        sinopsisDiv.textContent = "Mansfield Park sigue la vida de Fanny Price, una joven humilde que es enviada a vivir con sus ricos tíos, los Bertram, en la elegante finca de Mansfield Park. A lo largo de los años, Fanny crece en un entorno marcado por la riqueza, las normas sociales y las intrigas familiares, y se enfrenta a dilemas morales que ponen a prueba su carácter. Mientras desarrolla afecto por su primo Edmund, Fanny observa los errores, vanidades y pasiones de quienes la rodean, manteniéndose fiel a sus principios y valores. La novela explora temas de moralidad, matrimonio, clase social y las complejas relaciones humanas en la Inglaterra del siglo XIX.";
        analisisDiv.textContent = "Publicada en 1814, se distingue de las otras novelas de Austen por su tono más serio y reflexivo. Austen ofrece una profunda crítica social, mostrando cómo la riqueza y el estatus pueden corromper la conducta y cómo la virtud y la integridad de Fanny contrastan con la frivolidad de su entorno. La obra también destaca por su tratamiento del crecimiento moral y emocional de la protagonista: Fanny representa la sensatez y la rectitud frente a las tentaciones y el comportamiento cuestionable de la alta sociedad. Aunque inicialmente recibió críticas mixtas —algunos lectores la consideraron menos entretenida que Orgullo y Prejuicio o Sentido y Sensibilidad—, con el tiempo ha sido reconocida por su complejidad psicológica, su crítica social y su enfoque ético, consolidándose como una de las novelas más maduras y sofisticadas de Jane Austen."
    } else if (titulo == "Emma") {
        sinopsisDiv.textContent = "Emma narra la vida de Emma Woodhouse, una joven adinerada, hermosa y confiada en su propio juicio, que disfruta organizando la vida amorosa de quienes la rodean. Aunque se considera una experta casamentera, Emma se enfrenta a malentendidos, errores de percepción y lecciones sobre orgullo, prejuicio y autoconocimiento. Su relación con el reservado y sensato Sr. Knightley se desarrolla gradualmente, llevándola a reconocer sus propios sentimientos y limitaciones. La novela explora el crecimiento personal, la amistad, el amor y las sutilezas de la sociedad inglesa del siglo XIX."
        analisisDiv.textContent = "Publicada en 1815, es una de las obras más sofisticadas y complejas de Jane Austen. Destaca por su ingenio, su aguda observación de la psicología y las interacciones sociales, y por su humor sutil. La novela examina la arrogancia y la autoconfianza excesiva de la protagonista, mostrando cómo los errores de juicio y la interferencia en la vida ajena pueden tener consecuencias inesperadas. La recepción de Emma fue positiva desde su publicación, apreciando la maestría de Austen en la caracterización, la ironía y la crítica social. A lo largo de los años, ha sido elogiada como una de las novelas más maduras de la autora, destacando su exploración de la autonomía femenina, la moralidad y la complejidad de las relaciones humanas. Sus adaptaciones literarias y cinematográficas continúan haciendo que la obra sea ampliamente conocida y apreciada en la actualidad."
    } else if (titulo == "Abadía de Northanger") {
        sinopsisDiv.textContent = "La abadía de Northanger sigue a Catherine Morland, una joven ingenua y aficionada a las novelas góticas, que es invitada a la sociedad de Bath y luego a la misteriosa Abadía de Northanger. Catherine sueña con aventuras románticas y secretos oscuros, pero pronto descubre que la realidad es mucho más cotidiana y menos dramática de lo que sus novelas le habían hecho imaginar. A través de sus encuentros con la familia Tilney y la intrigante sociedad de Bath, Catherine aprende a diferenciar la fantasía de la realidad y a desarrollar su juicio y madurez personal. La novela combina romance, humor e ironía, explorando la educación emocional y social de una joven en la Inglaterra del siglo XVIII."
        analisisDiv.textContent = "Escrita entre 1798 y 1799 y publicada póstumamente en 1817, es una sátira de las novelas góticas populares en la época, al tiempo que mantiene la mirada crítica y perspicaz que caracteriza a Jane Austen. La obra muestra la evolución de Catherine desde la ingenuidad hacia la madurez, destacando la importancia del discernimiento y la prudencia frente a las fantasías románticas y los prejuicios. La novela destaca por su humor, ironía y metanarrativa: Austen comenta directamente sobre los clichés de la literatura gótica, creando un juego literario entre ficción y realidad. Su recepción inicial fue positiva, apreciando la originalidad de la crítica social y literaria, aunque más tarde ganó mayor reconocimiento al formar parte del canon austeniano. Hoy se valora tanto por su agudo ingenio como por su perspectiva sobre la formación de carácter y la interacción social de las jóvenes en la Inglaterra de su tiempo."
    } else if (titulo == "Persuación") {
        sinopsisDiv.textContent = "Persuasión sigue la historia de Anne Elliot, una mujer de 27 años que, años atrás, fue persuadida para rechazar la propuesta de matrimonio de su gran amor, el Capitán Frederick Wentworth, debido a su posición social más baja. Ahora, tras varios años de separación, Wentworth regresa exitoso y rico, y Anne debe enfrentar sus sentimientos y la posibilidad de un segundo romance. La novela explora temas de amor tardío, segundas oportunidades, perseverancia y las limitaciones sociales de la Inglaterra del siglo XIX."
        analisisDiv.textContent = "Publicada póstumamente en 1817, es la novela más madura y melancólica de Jane Austen. Destaca por su tono introspectivo y reflexivo, centrado en la evolución emocional de Anne, su prudencia y su capacidad de resiliencia frente a las decisiones pasadas. La obra ofrece una crítica sutil a las barreras sociales y económicas que afectan las relaciones y el matrimonio, y muestra cómo la experiencia y la madurez pueden conducir al verdadero entendimiento de uno mismo y de los demás. La recepción de Persuasión ha sido muy favorable, considerándola una obra profunda y emotiva que refleja con sensibilidad la psicología de sus personajes. Es apreciada por su delicadeza, su realismo social y su enfoque en las segundas oportunidades, consolidándola como un clásico imprescindible dentro del canon austeniano."
    } else {
        sinopsisDiv.textContent = "Selecciona una obra para ver la sinopsis.";
        analisisDiv.textContent = "Selecciona una obra para ver el analisis.";
    }
}

carrusel.addEventListener('slid.bs.carousel', actualizarSinopsis);

actualizarSinopsis();